/**
 * QGuard Cryptographic Fingerprint Database
 * 70 fingerprints for detecting quantum-vulnerable cryptography
 * across TLS, certificates, SSH, key files, blockchain, cloud/API, network protocols
 */

export type FingerprintCategory =
  | 'tls-cipher-suite'
  | 'tls-protocol'
  | 'certificate-oid'
  | 'ssh-algorithm'
  | 'key-file-header'
  | 'crypto-file-format'
  | 'hash-algorithm'
  | 'blockchain-wallet'
  | 'digital-signature'
  | 'network-protocol'
  | 'cloud-api'

export type QuantumThreat = 'shor' | 'grover' | 'both' | 'classical-broken'

export interface CryptoFingerprint {
  id: number
  identifier: string
  description: string
  category: FingerprintCategory
  algorithm: string
  quantumThreat: QuantumThreat
  riskScore: number           // 0-1000
  keySize?: number
  isQuantumVulnerable: boolean
  shorVulnerable: boolean     // Broken by Shor's algorithm
  groverImpact: boolean       // Weakened by Grover's algorithm
  pqcReplacement: string
  detectionPattern: string    // regex or string match pattern
}

/**
 * Complete database of 70 cryptographic fingerprints
 */
export const CRYPTO_FINGERPRINTS: CryptoFingerprint[] = [
  // ============================================================
  // TLS CIPHER SUITE FINGERPRINTS (1-10)
  // ============================================================
  {
    id: 1,
    identifier: 'TLS_RSA_WITH_AES_128_CBC_SHA',
    description: 'TLS cipher suite using RSA key exchange with AES-128-CBC and SHA-1 MAC',
    category: 'tls-cipher-suite',
    algorithm: 'RSA',
    quantumThreat: 'shor',
    riskScore: 750,
    isQuantumVulnerable: true,
    shorVulnerable: true,
    groverImpact: false,
    pqcReplacement: 'TLS 1.3 with ML-KEM hybrid key exchange',
    detectionPattern: 'TLS_RSA_WITH_AES_128_CBC_SHA',
  },
  {
    id: 2,
    identifier: 'TLS_RSA_WITH_AES_256_CBC_SHA',
    description: 'TLS cipher suite using RSA key exchange with AES-256-CBC and SHA-1 MAC',
    category: 'tls-cipher-suite',
    algorithm: 'RSA',
    quantumThreat: 'shor',
    riskScore: 740,
    isQuantumVulnerable: true,
    shorVulnerable: true,
    groverImpact: false,
    pqcReplacement: 'TLS 1.3 with ML-KEM hybrid key exchange',
    detectionPattern: 'TLS_RSA_WITH_AES_256_CBC_SHA',
  },
  {
    id: 3,
    identifier: 'TLS_RSA_WITH_AES_128_GCM_SHA256',
    description: 'TLS cipher suite using RSA key exchange with AES-128-GCM',
    category: 'tls-cipher-suite',
    algorithm: 'RSA',
    quantumThreat: 'shor',
    riskScore: 720,
    isQuantumVulnerable: true,
    shorVulnerable: true,
    groverImpact: false,
    pqcReplacement: 'TLS 1.3 with ML-KEM + AES-256-GCM',
    detectionPattern: 'TLS_RSA_WITH_AES_128_GCM_SHA256',
  },
  {
    id: 4,
    identifier: 'TLS_RSA_WITH_AES_256_GCM_SHA384',
    description: 'TLS cipher suite using RSA key exchange with AES-256-GCM',
    category: 'tls-cipher-suite',
    algorithm: 'RSA',
    quantumThreat: 'shor',
    riskScore: 700,
    isQuantumVulnerable: true,
    shorVulnerable: true,
    groverImpact: false,
    pqcReplacement: 'TLS 1.3 with ML-KEM hybrid key exchange',
    detectionPattern: 'TLS_RSA_WITH_AES_256_GCM_SHA384',
  },
  {
    id: 5,
    identifier: 'TLS_DHE_RSA_WITH_AES_128_CBC_SHA',
    description: 'TLS cipher suite using DHE-RSA key exchange with AES-128-CBC',
    category: 'tls-cipher-suite',
    algorithm: 'Diffie-Hellman + RSA',
    quantumThreat: 'shor',
    riskScore: 680,
    isQuantumVulnerable: true,
    shorVulnerable: true,
    groverImpact: false,
    pqcReplacement: 'TLS 1.3 with ML-KEM key exchange',
    detectionPattern: 'TLS_DHE_RSA_WITH_AES_128_CBC_SHA',
  },
  {
    id: 6,
    identifier: 'TLS_DHE_RSA_WITH_AES_256_CBC_SHA',
    description: 'TLS cipher suite using DHE-RSA key exchange with AES-256-CBC',
    category: 'tls-cipher-suite',
    algorithm: 'Diffie-Hellman + RSA',
    quantumThreat: 'shor',
    riskScore: 670,
    isQuantumVulnerable: true,
    shorVulnerable: true,
    groverImpact: false,
    pqcReplacement: 'TLS 1.3 with ML-KEM key exchange',
    detectionPattern: 'TLS_DHE_RSA_WITH_AES_256_CBC_SHA',
  },
  {
    id: 7,
    identifier: 'TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256',
    description: 'TLS cipher suite using ECDHE-RSA key exchange with AES-128-GCM',
    category: 'tls-cipher-suite',
    algorithm: 'ECDHE + RSA',
    quantumThreat: 'shor',
    riskScore: 620,
    isQuantumVulnerable: true,
    shorVulnerable: true,
    groverImpact: false,
    pqcReplacement: 'TLS 1.3 with X25519Kyber768 hybrid',
    detectionPattern: 'TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256',
  },
  {
    id: 8,
    identifier: 'TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384',
    description: 'TLS cipher suite using ECDHE-RSA key exchange with AES-256-GCM',
    category: 'tls-cipher-suite',
    algorithm: 'ECDHE + RSA',
    quantumThreat: 'shor',
    riskScore: 610,
    isQuantumVulnerable: true,
    shorVulnerable: true,
    groverImpact: false,
    pqcReplacement: 'TLS 1.3 with X25519Kyber768 hybrid',
    detectionPattern: 'TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384',
  },
  {
    id: 9,
    identifier: 'TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256',
    description: 'TLS cipher suite using ECDHE-ECDSA key exchange with AES-128-GCM',
    category: 'tls-cipher-suite',
    algorithm: 'ECDHE + ECDSA',
    quantumThreat: 'shor',
    riskScore: 600,
    isQuantumVulnerable: true,
    shorVulnerable: true,
    groverImpact: false,
    pqcReplacement: 'TLS 1.3 with ML-KEM + ML-DSA hybrid',
    detectionPattern: 'TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256',
  },
  {
    id: 10,
    identifier: 'TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384',
    description: 'TLS cipher suite using ECDHE-ECDSA key exchange with AES-256-GCM',
    category: 'tls-cipher-suite',
    algorithm: 'ECDHE + ECDSA',
    quantumThreat: 'shor',
    riskScore: 590,
    isQuantumVulnerable: true,
    shorVulnerable: true,
    groverImpact: false,
    pqcReplacement: 'TLS 1.3 with ML-KEM + ML-DSA hybrid',
    detectionPattern: 'TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384',
  },

  // ============================================================
  // TLS PROTOCOL VERSION FINGERPRINTS (11-15)
  // ============================================================
  {
    id: 11,
    identifier: 'TLS_1.0',
    description: 'TLS 1.0 protocol — deprecated, uses legacy cipher suites',
    category: 'tls-protocol',
    algorithm: 'TLS 1.0',
    quantumThreat: 'both',
    riskScore: 900,
    isQuantumVulnerable: true,
    shorVulnerable: true,
    groverImpact: true,
    pqcReplacement: 'TLS 1.3 with post-quantum key exchange',
    detectionPattern: '\\x03\\x01',
  },
  {
    id: 12,
    identifier: 'TLS_1.1',
    description: 'TLS 1.1 protocol — deprecated, uses legacy cipher suites',
    category: 'tls-protocol',
    algorithm: 'TLS 1.1',
    quantumThreat: 'both',
    riskScore: 850,
    isQuantumVulnerable: true,
    shorVulnerable: true,
    groverImpact: true,
    pqcReplacement: 'TLS 1.3 with post-quantum key exchange',
    detectionPattern: '\\x03\\x02',
  },
  {
    id: 13,
    identifier: 'SSLv3',
    description: 'SSLv3 protocol — critically deprecated, POODLE vulnerability',
    category: 'tls-protocol',
    algorithm: 'SSLv3',
    quantumThreat: 'classical-broken',
    riskScore: 980,
    isQuantumVulnerable: true,
    shorVulnerable: true,
    groverImpact: true,
    pqcReplacement: 'TLS 1.3',
    detectionPattern: '\\x03\\x00',
  },
  {
    id: 14,
    identifier: 'TLS_RENEGOTIATION_DEPRECATED',
    description: 'Deprecated TLS renegotiation extension',
    category: 'tls-protocol',
    algorithm: 'TLS renegotiation',
    quantumThreat: 'classical-broken',
    riskScore: 700,
    isQuantumVulnerable: false,
    shorVulnerable: false,
    groverImpact: false,
    pqcReplacement: 'TLS 1.3 (renegotiation removed)',
    detectionPattern: 'renegotiation_info',
  },
  {
    id: 15,
    identifier: 'TLS_COMPRESSION_ENABLED',
    description: 'TLS compression enabled — CRIME attack vector',
    category: 'tls-protocol',
    algorithm: 'TLS compression',
    quantumThreat: 'classical-broken',
    riskScore: 650,
    isQuantumVulnerable: false,
    shorVulnerable: false,
    groverImpact: false,
    pqcReplacement: 'Disable TLS compression',
    detectionPattern: 'compression_method',
  },

  // ============================================================
  // CERTIFICATE ALGORITHM OID FINGERPRINTS (16-25)
  // ============================================================
  {
    id: 16,
    identifier: 'OID_1.2.840.113549.1.1.1',
    description: 'RSA encryption OID — public key uses RSA algorithm',
    category: 'certificate-oid',
    algorithm: 'RSA',
    quantumThreat: 'shor',
    riskScore: 750,
    isQuantumVulnerable: true,
    shorVulnerable: true,
    groverImpact: false,
    pqcReplacement: 'ML-KEM (FIPS 203)',
    detectionPattern: '1.2.840.113549.1.1.1',
  },
  {
    id: 17,
    identifier: 'OID_1.2.840.113549.1.1.5',
    description: 'SHA-1 with RSA signature OID — doubly vulnerable',
    category: 'certificate-oid',
    algorithm: 'SHA1WithRSA',
    quantumThreat: 'both',
    riskScore: 920,
    isQuantumVulnerable: true,
    shorVulnerable: true,
    groverImpact: true,
    pqcReplacement: 'ML-DSA (FIPS 204)',
    detectionPattern: '1.2.840.113549.1.1.5',
  },
  {
    id: 18,
    identifier: 'OID_1.2.840.113549.1.1.11',
    description: 'SHA-256 with RSA signature OID',
    category: 'certificate-oid',
    algorithm: 'SHA256WithRSA',
    quantumThreat: 'shor',
    riskScore: 680,
    isQuantumVulnerable: true,
    shorVulnerable: true,
    groverImpact: false,
    pqcReplacement: 'ML-DSA (FIPS 204)',
    detectionPattern: '1.2.840.113549.1.1.11',
  },
  {
    id: 19,
    identifier: 'OID_1.2.840.113549.1.1.13',
    description: 'SHA-512 with RSA signature OID',
    category: 'certificate-oid',
    algorithm: 'SHA512WithRSA',
    quantumThreat: 'shor',
    riskScore: 660,
    isQuantumVulnerable: true,
    shorVulnerable: true,
    groverImpact: false,
    pqcReplacement: 'ML-DSA (FIPS 204)',
    detectionPattern: '1.2.840.113549.1.1.13',
  },
  {
    id: 20,
    identifier: 'OID_1.2.840.10045.4.3.2',
    description: 'ECDSA with SHA-256 signature OID',
    category: 'certificate-oid',
    algorithm: 'ECDSA-SHA256',
    quantumThreat: 'shor',
    riskScore: 640,
    isQuantumVulnerable: true,
    shorVulnerable: true,
    groverImpact: false,
    pqcReplacement: 'ML-DSA (FIPS 204)',
    detectionPattern: '1.2.840.10045.4.3.2',
  },
  {
    id: 21,
    identifier: 'OID_1.2.840.10045.4.3.3',
    description: 'ECDSA with SHA-384 signature OID',
    category: 'certificate-oid',
    algorithm: 'ECDSA-SHA384',
    quantumThreat: 'shor',
    riskScore: 630,
    isQuantumVulnerable: true,
    shorVulnerable: true,
    groverImpact: false,
    pqcReplacement: 'ML-DSA (FIPS 204)',
    detectionPattern: '1.2.840.10045.4.3.3',
  },
  {
    id: 22,
    identifier: 'OID_1.2.840.10045.2.1',
    description: 'Elliptic curve public key OID',
    category: 'certificate-oid',
    algorithm: 'ECC',
    quantumThreat: 'shor',
    riskScore: 650,
    isQuantumVulnerable: true,
    shorVulnerable: true,
    groverImpact: false,
    pqcReplacement: 'ML-KEM or ML-DSA',
    detectionPattern: '1.2.840.10045.2.1',
  },
  {
    id: 23,
    identifier: 'OID_1.3.132.0.10',
    description: 'secp256k1 curve OID — used by Bitcoin/Ethereum',
    category: 'certificate-oid',
    algorithm: 'secp256k1',
    quantumThreat: 'shor',
    riskScore: 780,
    isQuantumVulnerable: true,
    shorVulnerable: true,
    groverImpact: false,
    pqcReplacement: 'ML-DSA or SPHINCS+ for blockchain signatures',
    detectionPattern: '1.3.132.0.10',
  },
  {
    id: 24,
    identifier: 'OID_1.3.132.0.34',
    description: 'secp384r1 (P-384) curve OID',
    category: 'certificate-oid',
    algorithm: 'secp384r1',
    quantumThreat: 'shor',
    riskScore: 620,
    isQuantumVulnerable: true,
    shorVulnerable: true,
    groverImpact: false,
    pqcReplacement: 'ML-DSA (FIPS 204)',
    detectionPattern: '1.3.132.0.34',
  },
  {
    id: 25,
    identifier: 'OID_1.3.132.0.35',
    description: 'secp521r1 (P-521) curve OID',
    category: 'certificate-oid',
    algorithm: 'secp521r1',
    quantumThreat: 'shor',
    riskScore: 600,
    isQuantumVulnerable: true,
    shorVulnerable: true,
    groverImpact: false,
    pqcReplacement: 'ML-DSA (FIPS 204)',
    detectionPattern: '1.3.132.0.35',
  },

  // ============================================================
  // SSH ALGORITHM IDENTIFIERS (26-35)
  // ============================================================
  {
    id: 26,
    identifier: 'ssh-rsa',
    description: 'SSH RSA host key algorithm',
    category: 'ssh-algorithm',
    algorithm: 'RSA',
    quantumThreat: 'shor',
    riskScore: 740,
    isQuantumVulnerable: true,
    shorVulnerable: true,
    groverImpact: false,
    pqcReplacement: 'SSH with ML-DSA host keys',
    detectionPattern: 'ssh-rsa',
  },
  {
    id: 27,
    identifier: 'rsa-sha2-256',
    description: 'SSH RSA with SHA-256 signature',
    category: 'ssh-algorithm',
    algorithm: 'RSA-SHA256',
    quantumThreat: 'shor',
    riskScore: 680,
    isQuantumVulnerable: true,
    shorVulnerable: true,
    groverImpact: false,
    pqcReplacement: 'SSH with ML-DSA signatures',
    detectionPattern: 'rsa-sha2-256',
  },
  {
    id: 28,
    identifier: 'rsa-sha2-512',
    description: 'SSH RSA with SHA-512 signature',
    category: 'ssh-algorithm',
    algorithm: 'RSA-SHA512',
    quantumThreat: 'shor',
    riskScore: 660,
    isQuantumVulnerable: true,
    shorVulnerable: true,
    groverImpact: false,
    pqcReplacement: 'SSH with ML-DSA signatures',
    detectionPattern: 'rsa-sha2-512',
  },
  {
    id: 29,
    identifier: 'ssh-dss',
    description: 'SSH DSA host key algorithm — deprecated',
    category: 'ssh-algorithm',
    algorithm: 'DSA',
    quantumThreat: 'shor',
    riskScore: 880,
    isQuantumVulnerable: true,
    shorVulnerable: true,
    groverImpact: false,
    pqcReplacement: 'SSH with ML-DSA host keys',
    detectionPattern: 'ssh-dss',
  },
  {
    id: 30,
    identifier: 'ecdsa-sha2-nistp256',
    description: 'SSH ECDSA with NIST P-256 curve',
    category: 'ssh-algorithm',
    algorithm: 'ECDSA-P256',
    quantumThreat: 'shor',
    riskScore: 640,
    isQuantumVulnerable: true,
    shorVulnerable: true,
    groverImpact: false,
    pqcReplacement: 'SSH with ML-DSA signatures',
    detectionPattern: 'ecdsa-sha2-nistp256',
  },
  {
    id: 31,
    identifier: 'ecdsa-sha2-nistp384',
    description: 'SSH ECDSA with NIST P-384 curve',
    category: 'ssh-algorithm',
    algorithm: 'ECDSA-P384',
    quantumThreat: 'shor',
    riskScore: 630,
    isQuantumVulnerable: true,
    shorVulnerable: true,
    groverImpact: false,
    pqcReplacement: 'SSH with ML-DSA signatures',
    detectionPattern: 'ecdsa-sha2-nistp384',
  },
  {
    id: 32,
    identifier: 'ecdsa-sha2-nistp521',
    description: 'SSH ECDSA with NIST P-521 curve',
    category: 'ssh-algorithm',
    algorithm: 'ECDSA-P521',
    quantumThreat: 'shor',
    riskScore: 620,
    isQuantumVulnerable: true,
    shorVulnerable: true,
    groverImpact: false,
    pqcReplacement: 'SSH with ML-DSA signatures',
    detectionPattern: 'ecdsa-sha2-nistp521',
  },
  {
    id: 33,
    identifier: 'diffie-hellman-group1-sha1',
    description: 'SSH DH Group 1 (768-bit) with SHA-1 — critically weak',
    category: 'ssh-algorithm',
    algorithm: 'DH-Group1-SHA1',
    quantumThreat: 'both',
    riskScore: 950,
    isQuantumVulnerable: true,
    shorVulnerable: true,
    groverImpact: true,
    pqcReplacement: 'SSH with ML-KEM key exchange',
    detectionPattern: 'diffie-hellman-group1-sha1',
  },
  {
    id: 34,
    identifier: 'diffie-hellman-group14-sha1',
    description: 'SSH DH Group 14 (2048-bit) with SHA-1',
    category: 'ssh-algorithm',
    algorithm: 'DH-Group14-SHA1',
    quantumThreat: 'both',
    riskScore: 760,
    isQuantumVulnerable: true,
    shorVulnerable: true,
    groverImpact: true,
    pqcReplacement: 'SSH with ML-KEM key exchange',
    detectionPattern: 'diffie-hellman-group14-sha1',
  },
  {
    id: 35,
    identifier: 'curve25519-sha256',
    description: 'SSH Curve25519 key exchange — quantum vulnerable via Shor',
    category: 'ssh-algorithm',
    algorithm: 'Curve25519',
    quantumThreat: 'shor',
    riskScore: 500,
    isQuantumVulnerable: true,
    shorVulnerable: true,
    groverImpact: false,
    pqcReplacement: 'SSH with ML-KEM hybrid (Curve25519 + Kyber)',
    detectionPattern: 'curve25519-sha256',
  },

  // ============================================================
  // KEY FILE HEADER FINGERPRINTS (36-40)
  // ============================================================
  {
    id: 36,
    identifier: 'RSA_PRIVATE_KEY_PEM',
    description: 'PEM-encoded RSA private key file',
    category: 'key-file-header',
    algorithm: 'RSA',
    quantumThreat: 'shor',
    riskScore: 800,
    isQuantumVulnerable: true,
    shorVulnerable: true,
    groverImpact: false,
    pqcReplacement: 'ML-KEM or ML-DSA key pair',
    detectionPattern: '-----BEGIN RSA PRIVATE KEY-----',
  },
  {
    id: 37,
    identifier: 'EC_PRIVATE_KEY_PEM',
    description: 'PEM-encoded elliptic curve private key file',
    category: 'key-file-header',
    algorithm: 'ECC',
    quantumThreat: 'shor',
    riskScore: 780,
    isQuantumVulnerable: true,
    shorVulnerable: true,
    groverImpact: false,
    pqcReplacement: 'ML-DSA key pair',
    detectionPattern: '-----BEGIN EC PRIVATE KEY-----',
  },
  {
    id: 38,
    identifier: 'DSA_PRIVATE_KEY_PEM',
    description: 'PEM-encoded DSA private key file — deprecated',
    category: 'key-file-header',
    algorithm: 'DSA',
    quantumThreat: 'shor',
    riskScore: 880,
    isQuantumVulnerable: true,
    shorVulnerable: true,
    groverImpact: false,
    pqcReplacement: 'ML-DSA key pair',
    detectionPattern: '-----BEGIN DSA PRIVATE KEY-----',
  },
  {
    id: 39,
    identifier: 'OPENSSH_PRIVATE_KEY',
    description: 'OpenSSH private key format (may contain RSA/ECDSA/Ed25519)',
    category: 'key-file-header',
    algorithm: 'OpenSSH (mixed)',
    quantumThreat: 'shor',
    riskScore: 650,
    isQuantumVulnerable: true,
    shorVulnerable: true,
    groverImpact: false,
    pqcReplacement: 'ML-DSA SSH key pair',
    detectionPattern: '-----BEGIN OPENSSH PRIVATE KEY-----',
  },
  {
    id: 40,
    identifier: 'PGP_PRIVATE_KEY_BLOCK',
    description: 'PGP/GPG private key block — typically RSA or ECC based',
    category: 'key-file-header',
    algorithm: 'PGP (RSA/ECC)',
    quantumThreat: 'shor',
    riskScore: 760,
    isQuantumVulnerable: true,
    shorVulnerable: true,
    groverImpact: false,
    pqcReplacement: 'PQC-enabled PGP with ML-DSA',
    detectionPattern: '-----BEGIN PGP PRIVATE KEY BLOCK-----',
  },

  // ============================================================
  // CRYPTOGRAPHIC FILE FORMAT FINGERPRINTS (41-45)
  // ============================================================
  {
    id: 41,
    identifier: 'PKCS12_HEADER',
    description: 'PKCS#12 keystore file (binary format 0x30 0x82)',
    category: 'crypto-file-format',
    algorithm: 'PKCS#12',
    quantumThreat: 'shor',
    riskScore: 700,
    isQuantumVulnerable: true,
    shorVulnerable: true,
    groverImpact: false,
    pqcReplacement: 'PQC keystore format',
    detectionPattern: '3082',
  },
  {
    id: 42,
    identifier: 'PKCS8_PRIVATE_KEY',
    description: 'PKCS#8 private key format',
    category: 'crypto-file-format',
    algorithm: 'PKCS#8',
    quantumThreat: 'shor',
    riskScore: 700,
    isQuantumVulnerable: true,
    shorVulnerable: true,
    groverImpact: false,
    pqcReplacement: 'ML-KEM/ML-DSA key format',
    detectionPattern: '-----BEGIN PRIVATE KEY-----',
  },
  {
    id: 43,
    identifier: 'X509_DER_CERTIFICATE',
    description: 'X.509 certificate in DER encoding',
    category: 'crypto-file-format',
    algorithm: 'X.509',
    quantumThreat: 'shor',
    riskScore: 650,
    isQuantumVulnerable: true,
    shorVulnerable: true,
    groverImpact: false,
    pqcReplacement: 'PQC X.509 certificates with ML-DSA',
    detectionPattern: '3082',
  },
  {
    id: 44,
    identifier: 'PEM_CERTIFICATE',
    description: 'PEM-encoded X.509 certificate',
    category: 'crypto-file-format',
    algorithm: 'X.509 (PEM)',
    quantumThreat: 'shor',
    riskScore: 640,
    isQuantumVulnerable: true,
    shorVulnerable: true,
    groverImpact: false,
    pqcReplacement: 'PQC X.509 with ML-DSA signatures',
    detectionPattern: '-----BEGIN CERTIFICATE-----',
  },
  {
    id: 45,
    identifier: 'JAVA_KEYSTORE_JKS',
    description: 'Java KeyStore (JKS) file signature',
    category: 'crypto-file-format',
    algorithm: 'JKS',
    quantumThreat: 'shor',
    riskScore: 720,
    isQuantumVulnerable: true,
    shorVulnerable: true,
    groverImpact: false,
    pqcReplacement: 'PKCS#12 with PQC algorithms',
    detectionPattern: 'feedfeed',
  },

  // ============================================================
  // HASH ALGORITHM FINGERPRINTS (46-50)
  // ============================================================
  {
    id: 46,
    identifier: 'MD5_DIGEST',
    description: 'MD5 hash (128-bit) — completely broken classically',
    category: 'hash-algorithm',
    algorithm: 'MD5',
    quantumThreat: 'classical-broken',
    riskScore: 990,
    keySize: 128,
    isQuantumVulnerable: true,
    shorVulnerable: false,
    groverImpact: true,
    pqcReplacement: 'SHA-3 or SHA-256',
    detectionPattern: 'md5|MD5',
  },
  {
    id: 47,
    identifier: 'SHA1_DIGEST',
    description: 'SHA-1 hash (160-bit) — collision attacks demonstrated',
    category: 'hash-algorithm',
    algorithm: 'SHA-1',
    quantumThreat: 'classical-broken',
    riskScore: 950,
    keySize: 160,
    isQuantumVulnerable: true,
    shorVulnerable: false,
    groverImpact: true,
    pqcReplacement: 'SHA-3 or SHA-256',
    detectionPattern: 'sha1|SHA-1|SHA1',
  },
  {
    id: 48,
    identifier: 'SHA256_DIGEST',
    description: 'SHA-256 hash (256-bit) — Grover reduces to 128-bit security',
    category: 'hash-algorithm',
    algorithm: 'SHA-256',
    quantumThreat: 'grover',
    riskScore: 200,
    keySize: 256,
    isQuantumVulnerable: false,
    shorVulnerable: false,
    groverImpact: true,
    pqcReplacement: 'SHA-256 adequate; consider SHA-3 for future-proofing',
    detectionPattern: 'sha256|SHA-256|SHA256',
  },
  {
    id: 49,
    identifier: 'SHA384_DIGEST',
    description: 'SHA-384 hash (384-bit) — quantum safe',
    category: 'hash-algorithm',
    algorithm: 'SHA-384',
    quantumThreat: 'grover',
    riskScore: 100,
    keySize: 384,
    isQuantumVulnerable: false,
    shorVulnerable: false,
    groverImpact: true,
    pqcReplacement: 'Quantum safe — no migration needed',
    detectionPattern: 'sha384|SHA-384|SHA384',
  },
  {
    id: 50,
    identifier: 'SHA512_DIGEST',
    description: 'SHA-512 hash (512-bit) — quantum safe',
    category: 'hash-algorithm',
    algorithm: 'SHA-512',
    quantumThreat: 'grover',
    riskScore: 50,
    keySize: 512,
    isQuantumVulnerable: false,
    shorVulnerable: false,
    groverImpact: true,
    pqcReplacement: 'Quantum safe — no migration needed',
    detectionPattern: 'sha512|SHA-512|SHA512',
  },

  // ============================================================
  // BLOCKCHAIN WALLET FINGERPRINTS (51-55)
  // ============================================================
  {
    id: 51,
    identifier: 'BITCOIN_WALLET_DAT',
    description: 'Bitcoin wallet.dat file structure — uses secp256k1 ECDSA',
    category: 'blockchain-wallet',
    algorithm: 'secp256k1 ECDSA',
    quantumThreat: 'shor',
    riskScore: 820,
    isQuantumVulnerable: true,
    shorVulnerable: true,
    groverImpact: false,
    pqcReplacement: 'PQC-based wallet with ML-DSA signatures',
    detectionPattern: 'wallet\\.dat',
  },
  {
    id: 52,
    identifier: 'ETHEREUM_KEYSTORE_JSON',
    description: 'Ethereum keystore JSON format — uses secp256k1 ECDSA',
    category: 'blockchain-wallet',
    algorithm: 'secp256k1 ECDSA',
    quantumThreat: 'shor',
    riskScore: 810,
    isQuantumVulnerable: true,
    shorVulnerable: true,
    groverImpact: false,
    pqcReplacement: 'PQC-based keystore with ML-DSA',
    detectionPattern: '"crypto":\\s*\\{.*"cipher"',
  },
  {
    id: 53,
    identifier: 'BIP32_HD_WALLET',
    description: 'BIP-32 hierarchical deterministic wallet key format',
    category: 'blockchain-wallet',
    algorithm: 'secp256k1 ECDSA',
    quantumThreat: 'shor',
    riskScore: 800,
    isQuantumVulnerable: true,
    shorVulnerable: true,
    groverImpact: false,
    pqcReplacement: 'PQC HD wallet with ML-DSA derivation',
    detectionPattern: 'xpub|xprv|zpub|zprv',
  },
  {
    id: 54,
    identifier: 'BIP39_MNEMONIC_SEED',
    description: 'BIP-39 mnemonic seed phrase structure',
    category: 'blockchain-wallet',
    algorithm: 'secp256k1 ECDSA (derived)',
    quantumThreat: 'shor',
    riskScore: 790,
    isQuantumVulnerable: true,
    shorVulnerable: true,
    groverImpact: false,
    pqcReplacement: 'PQC seed derivation with quantum-safe KDF',
    detectionPattern: 'mnemonic|seed\\s*phrase',
  },
  {
    id: 55,
    identifier: 'SECP256K1_PUBLIC_KEY',
    description: 'secp256k1 public key format (Bitcoin/Ethereum)',
    category: 'blockchain-wallet',
    algorithm: 'secp256k1',
    quantumThreat: 'shor',
    riskScore: 830,
    isQuantumVulnerable: true,
    shorVulnerable: true,
    groverImpact: false,
    pqcReplacement: 'ML-DSA public key',
    detectionPattern: '(04|02|03)[0-9a-fA-F]{64}',
  },

  // ============================================================
  // DIGITAL SIGNATURE FORMAT FINGERPRINTS (56-60)
  // ============================================================
  {
    id: 56,
    identifier: 'ASN1_DER_ECDSA_SIGNATURE',
    description: 'ASN.1 DER-encoded ECDSA signature structure',
    category: 'digital-signature',
    algorithm: 'ECDSA',
    quantumThreat: 'shor',
    riskScore: 700,
    isQuantumVulnerable: true,
    shorVulnerable: true,
    groverImpact: false,
    pqcReplacement: 'ML-DSA (FIPS 204) signature',
    detectionPattern: '3045022100|3046022100',
  },
  {
    id: 57,
    identifier: 'RSA_PKCS1_V15_SIGNATURE',
    description: 'RSA PKCS#1 v1.5 signature format',
    category: 'digital-signature',
    algorithm: 'RSA PKCS#1 v1.5',
    quantumThreat: 'shor',
    riskScore: 750,
    isQuantumVulnerable: true,
    shorVulnerable: true,
    groverImpact: false,
    pqcReplacement: 'ML-DSA (FIPS 204) signature',
    detectionPattern: 'PKCS1v15|pkcs1',
  },
  {
    id: 58,
    identifier: 'RSA_PSS_SIGNATURE',
    description: 'RSA-PSS signature format — better padding but still RSA',
    category: 'digital-signature',
    algorithm: 'RSA-PSS',
    quantumThreat: 'shor',
    riskScore: 680,
    isQuantumVulnerable: true,
    shorVulnerable: true,
    groverImpact: false,
    pqcReplacement: 'ML-DSA (FIPS 204) signature',
    detectionPattern: 'RSA-PSS|rsaPSS',
  },
  {
    id: 59,
    identifier: 'DSA_SIGNATURE',
    description: 'DSA signature structure — deprecated',
    category: 'digital-signature',
    algorithm: 'DSA',
    quantumThreat: 'shor',
    riskScore: 860,
    isQuantumVulnerable: true,
    shorVulnerable: true,
    groverImpact: false,
    pqcReplacement: 'ML-DSA (FIPS 204) signature',
    detectionPattern: 'dsa-sha|DSA',
  },
  {
    id: 60,
    identifier: 'ED25519_SIGNATURE',
    description: 'Ed25519 signature format — quantum vulnerable via Shor',
    category: 'digital-signature',
    algorithm: 'Ed25519',
    quantumThreat: 'shor',
    riskScore: 520,
    isQuantumVulnerable: true,
    shorVulnerable: true,
    groverImpact: false,
    pqcReplacement: 'ML-DSA or SPHINCS+ signature',
    detectionPattern: 'ed25519|Ed25519',
  },

  // ============================================================
  // NETWORK PROTOCOL FINGERPRINTS (61-65)
  // ============================================================
  {
    id: 61,
    identifier: 'IKEV1_NEGOTIATION',
    description: 'IKEv1 negotiation identifier — legacy IPSec',
    category: 'network-protocol',
    algorithm: 'IKEv1 (DH)',
    quantumThreat: 'shor',
    riskScore: 850,
    isQuantumVulnerable: true,
    shorVulnerable: true,
    groverImpact: false,
    pqcReplacement: 'IKEv2 with ML-KEM key exchange',
    detectionPattern: 'IKEv1|ikev1',
  },
  {
    id: 62,
    identifier: 'IKEV2_DH_GROUPS',
    description: 'IKEv2 Diffie-Hellman groups',
    category: 'network-protocol',
    algorithm: 'IKEv2 (DH)',
    quantumThreat: 'shor',
    riskScore: 650,
    isQuantumVulnerable: true,
    shorVulnerable: true,
    groverImpact: false,
    pqcReplacement: 'IKEv2 with ML-KEM hybrid',
    detectionPattern: 'IKEv2|ikev2',
  },
  {
    id: 63,
    identifier: 'IPSEC_ESP_ENCRYPTION',
    description: 'IPSec ESP encryption identifiers',
    category: 'network-protocol',
    algorithm: 'IPSec ESP',
    quantumThreat: 'shor',
    riskScore: 600,
    isQuantumVulnerable: true,
    shorVulnerable: true,
    groverImpact: false,
    pqcReplacement: 'IPSec with PQC key exchange',
    detectionPattern: 'ESP|ipsec',
  },
  {
    id: 64,
    identifier: 'OPENVPN_TLS_AUTH',
    description: 'OpenVPN TLS authentication markers',
    category: 'network-protocol',
    algorithm: 'OpenVPN (RSA/DH)',
    quantumThreat: 'shor',
    riskScore: 630,
    isQuantumVulnerable: true,
    shorVulnerable: true,
    groverImpact: false,
    pqcReplacement: 'OpenVPN with PQC TLS configuration',
    detectionPattern: 'openvpn|tls-auth',
  },
  {
    id: 65,
    identifier: 'WIREGUARD_PUBLIC_KEY',
    description: 'WireGuard public key format (Curve25519)',
    category: 'network-protocol',
    algorithm: 'Curve25519',
    quantumThreat: 'shor',
    riskScore: 500,
    isQuantumVulnerable: true,
    shorVulnerable: true,
    groverImpact: false,
    pqcReplacement: 'WireGuard with ML-KEM hybrid',
    detectionPattern: 'wireguard|WireGuard',
  },

  // ============================================================
  // CLOUD & API CRYPTOGRAPHY FINGERPRINTS (66-70)
  // ============================================================
  {
    id: 66,
    identifier: 'JWT_ALG_RS256',
    description: 'JWT signed with RS256 (RSA-SHA256)',
    category: 'cloud-api',
    algorithm: 'RSA-SHA256',
    quantumThreat: 'shor',
    riskScore: 720,
    isQuantumVulnerable: true,
    shorVulnerable: true,
    groverImpact: false,
    pqcReplacement: 'JWT with ML-DSA signature algorithm',
    detectionPattern: '"alg"\\s*:\\s*"RS256"',
  },
  {
    id: 67,
    identifier: 'JWT_ALG_ES256',
    description: 'JWT signed with ES256 (ECDSA P-256)',
    category: 'cloud-api',
    algorithm: 'ECDSA-P256',
    quantumThreat: 'shor',
    riskScore: 680,
    isQuantumVulnerable: true,
    shorVulnerable: true,
    groverImpact: false,
    pqcReplacement: 'JWT with ML-DSA signature algorithm',
    detectionPattern: '"alg"\\s*:\\s*"ES256"',
  },
  {
    id: 68,
    identifier: 'OAUTH_TOKEN_SIGNATURE',
    description: 'OAuth token signature — typically RSA or ECDSA based',
    category: 'cloud-api',
    algorithm: 'OAuth (RSA/ECDSA)',
    quantumThreat: 'shor',
    riskScore: 700,
    isQuantumVulnerable: true,
    shorVulnerable: true,
    groverImpact: false,
    pqcReplacement: 'OAuth with PQC token signatures',
    detectionPattern: 'oauth|OAuth|bearer',
  },
  {
    id: 69,
    identifier: 'TLS_CLIENT_CERTIFICATE_AUTH',
    description: 'TLS mutual authentication using client certificates',
    category: 'cloud-api',
    algorithm: 'TLS client cert (RSA/ECC)',
    quantumThreat: 'shor',
    riskScore: 660,
    isQuantumVulnerable: true,
    shorVulnerable: true,
    groverImpact: false,
    pqcReplacement: 'ML-DSA client certificates',
    detectionPattern: 'client_certificate|mutual_tls|mTLS',
  },
  {
    id: 70,
    identifier: 'API_HMAC_SIGNATURE',
    description: 'API HMAC signature headers — symmetric, Grover impact only',
    category: 'cloud-api',
    algorithm: 'HMAC',
    quantumThreat: 'grover',
    riskScore: 250,
    isQuantumVulnerable: false,
    shorVulnerable: false,
    groverImpact: true,
    pqcReplacement: 'HMAC-SHA256 or higher — adequate with 256+ bit keys',
    detectionPattern: 'HMAC|hmac|X-Signature',
  },
]

/**
 * Lookup a fingerprint by identifier
 */
export function findFingerprint(identifier: string): CryptoFingerprint | undefined {
  return CRYPTO_FINGERPRINTS.find((fp) => fp.identifier === identifier)
}

/**
 * Get all fingerprints for a category
 */
export function getFingerprintsByCategory(category: FingerprintCategory): CryptoFingerprint[] {
  return CRYPTO_FINGERPRINTS.filter((fp) => fp.category === category)
}

/**
 * Get all quantum-vulnerable fingerprints
 */
export function getVulnerableFingerprints(): CryptoFingerprint[] {
  return CRYPTO_FINGERPRINTS.filter((fp) => fp.isQuantumVulnerable)
}

/**
 * Get fingerprints vulnerable to Shor's algorithm
 */
export function getShorVulnerableFingerprints(): CryptoFingerprint[] {
  return CRYPTO_FINGERPRINTS.filter((fp) => fp.shorVulnerable)
}

/**
 * Match content against fingerprint detection patterns
 */
export function detectFingerprints(content: string): CryptoFingerprint[] {
  const matches: CryptoFingerprint[] = []
  for (const fp of CRYPTO_FINGERPRINTS) {
    try {
      const regex = new RegExp(fp.detectionPattern, 'i')
      if (regex.test(content)) {
        matches.push(fp)
      }
    } catch {
      // If regex is invalid, try simple string match
      if (content.includes(fp.detectionPattern)) {
        matches.push(fp)
      }
    }
  }
  return matches
}
